include:
  - path: ./common.yml
    env_file: ./.env

services:
  book_assistant:
    build: book_assistant

    environment:
      WEB_CONCURRENCY: "3"
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      DIAL_URL: "http://core:8080"
